# Generated by Django 4.2 on 2025-08-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='notified_10min',
            field=models.BooleanField(default=False),
        ),
    ]
